name: my_comic_app_v2
description: "A new Flutter project."
publish_to: 'none' # This prevents the package from being accidentally published to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  path_provider: ^2.1.4
  speech_to_text: ^6.4.0
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.2.0
  permission_handler: ^11.3.1
  image_gallery_saver: ^2.0.3
  device_info_plus: ^8.0.0
  image: ^3.0.1

  cupertino_icons: ^1.0.8
  google_generative_ai: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.11.0  # Add this line

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.jpg"  # Path to your app icon image
  adaptive_icon_background: "#ffffff"  # Optional for Android adaptive icons

flutter:
  uses-material-design: true

  assets:
    - assets/dog/
    - assets/cat/
    - assets/google_logo.png
    - lib/.env

  fonts:
    - family: ComicSans
      fonts:
        - asset: fonts/Comic Sans MS.ttf

